release-schema: add lot object to release schema, update examples in …
open-contracting-extensions/ocds_coveredBy_extension pull request #7
Opened 2023-03-02 12:10 UTC by odscjen

…README.md, add code to codelist

Hopefully another straightforward update to account for eforms requirements. I've altered the description slightly to refer to "treaties and directives" as we're adding EU-Clean Vehicles Directive to this as it fit the semantics of this extension but not the semantics of the legal basis extension.

The codelist test is failing, I think because it's objecting to the presence of a - in the code, but this code style is following the guidance in this extension so I've ignored it for now.

2023-03-02 16:22 UTC, jpmckinney commented
I've added the code pattern to codelist-schema.json in standard-maintenance-scripts. Tests should pass if re-run.

2023-03-13 21:14 UTC, duncandewhurst requested changes

2023-03-13 21:14 UTC, duncandewhurst commented on README.md
> +A treaty, like the Agreement on Government Procurement (GPA), can require a member to indicate that a contracting process is covered by it. The `coveredBy` field should be used to meet such requireme
Should we add a sentence to explain the usage of the extension in the context of directives?

```suggestion
A treaty, like the Agreement on Government Procurement (GPA), can require a member to indicate that a contracting process is covered by it. Similarly, a legislative standard for publishing procurement data, like [eForms](https://single-market-economy.ec.europa.eu/single-market/public-procurement/digital-procurement/eforms_en) in the European Union, can allow contracting authorities to indicate that a lot is covered by a directive, like the [Clean Vehicles Directive](https://transport.ec.europa.eu/transport-themes/clean-transport-urban-transport/clean-and-energy-efficient-vehicles/clean-vehicles-directive_en). The `coveredBy` field should be used to meet such requirements.
```

2023-03-13 21:14 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The treaties and directives that the contracting process for this lot is covered by.",
Slight amendment to clarify that the field should only be used for the treaties and directives for the specific lot.

```suggestion
          "description": "The treaties and directives that the lot is covered by.",
```

2023-03-29 21:30 UTC, duncandewhurst approved these changes
Looks good. You can request a review from James, now.

2023-04-27 01:48 UTC, jpmckinney approved these changes
I made two commits to simplify the semantics. The extension is about international legal instruments (EU directives are legal acts that are transposed into national law). "Directives" on its own means different things across jurisdictions.

Also, the code in the changelog needed single quotes, not double quotes.

2023-04-27 01:48 UTC, merged